spring: 
    datasource:
        generate-unique-name: false
        name: tacocloud
    data: 
      rest:
        base-path: /data-api
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: http://localhost:9000/oauth2/jwks
          