spring: 
    datasource:
        generate-unique-name: false
        name: tacocloud

    data: 
      rest:
        base-path: /data-api

    jms:
      template:
        default-destination: TacoQ
    
    artemis:
      mode: native
      host: 0.0.0.0
      port: 61616
      user: owl
      password: root